spring.application.name=catan
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-exclude=playground-results/**
playground.headless.enabled=true